### ISSUE TITLE
Incorporate tech review comments for 0.1.7 release

### ISSUE THREAD

**Issue by madison-feshuk** [USEPA/CompTox-ToxCast-tcplFit2#97]
Creating a catch all ticket so we can incorporate tech reviewer comments when we receive them 

- [x] Under imposing upper BMD bounds section: fix "censoring" to "bounding" in table
- [x] Add glossary of output terms

**Comment by madison-feshuk** [comment]
Tech review comments from Kelsey: "I wasn’t sure of the best way to provide comments on the html document, so I listed them in the attached Word doc organized by vignette section. I noticed several typos in the writing and captured some of them in the attached document, but this was difficult to do so I eventually stopped.

I noted several places that need clarification, but the biggest issues I noticed were:

- [ ] 	Necessary packages for running the code were not always included (e.g., ggplot2, gridExtra, dplyr)
- [ ] 	The code in Concentration-response Modeling for tcpl-like data without a database connection couldn’t be run because the data weren’t available
- [ ] 	Subsetting the data to log10 concentrations <= -2 in some of the examples for baseline calculations doesn’t seem to match the ‘two lowest concentrations’ baseline definition elsewhere because some series seem to have more than two concentrations <= -2.
- [ ] 	Some code sections could use more explanation or could be broken up into more steps for clarity
- [ ] 	I was surprised the BMDL and BMDU were not shifted on the log10 scale in the bounded BMD examples, but I don’t know all the details about those calculations.
- [ ] 	The biphasic AUC calculations will likely be difficult for users, and the example calculation doesn’t use a fitted model, which may also be confusing.
- [ ] 	In Model Details, the figures with concentrations on the log scale should have the concentration series start at a non-zero number and have greater resolution [e.g., ex_conc3 <- seq(0.01, 100, length.out = 1000)]
- [ ] 	The explanation of the impact of p in the exp3 and exp5 models did not seem completely accurate to me."

[tcplfit2_KV_comments.docx](https://github.com/user-attachments/files/16591574/tcplfit2_KV_comments.docx)

**Comment by brown-jason** [comment]
Kelsey Vitense

Comments on tcplfit2 release

Introduction

- [ ] •	Hyphenate instances of “concentration-response” 
- [ ] •	Typo in “high-throughput screening”
- [ ] •	Hyphenation is not consistent throughout document for ‘curve fitting’ (vs. ‘curve-fitting’), ‘hit calling’, or variations on those phrases.
- [ ] •	Check for instances of ‘tcplfit2’ not having the R package font
- [ ] •	Capitalize ‘benchmark dose’ to match capitalized “Benchmark Response”?
- [ ] •	‘Continuous hit call in tcplfit2 are is defined as…’
- [ ] •	Are the three proportional weights probabilities? As written, it is not clear to me how the three criteria listed translate quantitatively to weights.
- [ ] •	“While Although developed primarily to for bioactivity data curve -fitting…”

Concentration-response Modeling for a Single Series with concRespCore

- [ ] •	Capitalize the ‘R’ in ‘Concentration-Response Modeling’ titles
- [ ] •	Period or semicolon after “This example shows how to use the concRespCore function;, “
- [ ] •	row inputs
- [ ] o	resp: “These should be input as pairs of conc and resp values” is somewhat confusing and could be either deleted or reworded.
- [ ] o	cutoff: please clarify what is meant by “some multiple (typically 3) of the median absolute deviation around the baseline (BMAD), where the baseline is defined as the two lowest concentrations.” That is, do you mean a multiple of the BMAD above or below the baseline response, defined as the median or mean response at the two lowest concentrations – or something more specific like this? 
- [ ] o	bmed: data is are 
- [ ] o	onesd: do you mean ‘one standard deviation at the baseline’, meaning it is the actual value of the SD of the response at baseline, or do you mean onesd is one standard deviation above or below the baseline response? Maybe it doesn’t matter if the response is centered, but it seems that the responses wouldn’t have to be centered given that you can provide the bmed parameter.
- [ ] 	Also is this the correct definition of the BMR here? In the first example below of running concRespCore(), with onesd=0.5 and the default bmr_scale=1.349, bmr=0.5/1.349=0.371. But the output of running the function says bmr=0.6745. Please clarify.
- [ ] •	Additional arguments
- [ ] o	errfun: I assume there is a reason why t-distribution with df=4 is used that is documented elsewhere?
- [ ] o	poly2.biphasic typos: check for typos
- [ ] o	fitmodels: check for typos
- [ ] •	Code
- [ ] o	Suggest including code or instructions to install and load tcplfit2 package
- [ ] o	Suggest including code for printing the res object for clarity
- [ ] o	Typo: plotts
- [ ] o	I needed to load ggplot2 library separately in order for the concRespPlot2() function to work. That is, the code doesn’t work just by loading the tcplfit2 library.

Concentration-response Modeling for Multiple Series with tcplfit2_core and tcplhit2_core

- [ ] •	“This example shows how to fit fitting…”
- [ ] •	“using the tcplfit2_core and tcplhit2_core functions sequentially.”
- [ ] •	“contains model parameters for all models fit to the concentration-response series provided”
- [ ] •	In the interest of time, I stopped correcting typos and grammatical errors here. Please carefully check the document to 

improve the writing.

- [ ] •	Does the pre-processing that includes transformation of response values imply the response data have been centered? If so, please be specific because it helps the reader understand how the cutoff is determined, and why it is just 3*bmad in the example code and not bmed+3*bmad or similar.
- [ ] •	What does this sentence mean: “For this example, 6 out of 100 available from samples from mc3 are selected.” It looks like there are 100 chemicals but 186 unique spids? Should this say 6 out of 186 series? Can you clarify what ‘sample’ means in this context?
- [ ] •	Code
- [ ] o	Can you show the code in a way that doesn’t require the user to scroll?
- [ ] o	Suggest showing a summary of mc3 with str() or head() and explaining what the columns are.
- [ ] o	Please add comments for why <= -2 concentration was selected for baseline. Is this consistent with the two lowest dose definition of baseline described above? If so, it would help to include that explanation here. If not, please modify above description of baseline. It looks like chemicals can have more than 2 dose levels below -2 in this dataset so please check.
- [ ] o	Instead of “select six samples”, is it more correct to say “select six series”? ‘Samples’ is confusing to me, but I’m not sure how you’re using the terms samples vs. series here.
- [ ] o	Suggest explaining ‘bidirectional’ and ‘force.fit’ arguments
- [ ] 	For ‘bidirectional=TRUE’ does the cutoff need to be specified in both directions? 
- [ ] •	Structure of Hill elements
- [ ] o	Why is ‘rme’ used instead of rmse? Highly recommend using rmse instead.
- [ ] o	I don’t understand what the ‘er’ term is (the numeric error term). Can you please add additional text to explain. Same for er_sd.
- [ ] •	grid.arrange does not work without loading gridExtra package
- [ ] o	Also it might help to show the name of the chemical above each panel?
- [ ] •	Suggest showing the code or explaining that you are printing the ‘result_table’ object because it is not clear that this is the table you are showing.
- [ ] •	For plotting best model fit, I would delete “(e.g. one with a significant concentration-responses)”. You’ve already explained that it’s the winning model, and you didn’t explicitly do significance testing, it’s just the lowest AIC.

Concentration-response Modeling for tcpl-like data without a database connection

- [ ] •	Suggest always using ‘because’ in place of ‘since’ for clarity.
- [ ] •	It would be extremely helpful if the example level 0 table (mc0) could be available as part of the package so that the user can run the code. Vignettes should be able to be run as stand-alone examples to be most instructive.
- [ ] •	It is difficult for me to review the code in this section without the ‘dat’ object being available and without any of the code output being shown.
- [ ] •	I don’t think most people will be familiar with the “:=” operator. Please add comments in the code to explain what it does. Also does this require the data.table package or does it run with base R? If it requires data.table, this needs to be explained.
- [ ] o	I suggest rewriting the code to break it out into more steps so that the calculations and assignments aren’t contained inside the dat brackets. If that’s not possible, please provide more explanation/comments for the typical R user.
- [ ] •	The code could use more comments in the ‘Source Data Formatting’ and ‘Normalization’ sections.
- [ ] •	In Dose-Response Curve Fitting, is the second-to-last code chunk supposed to be deleted? And again, I’m not sure how users can currently run this code.
- [ ] o	Also, the behavior of the bidirectional=TRUE option hasn’t been explained.
- [ ] •	Again, it might help to show how to label the panels in grid.arrange with the chemical name or some other identifier. 

Bounding the Benchmark Dose (BMD)

- [ ] •	Typo “an lower”
Imposing Lower BMD Bounds
- [ ] •	Please print code block without need to scroll
- [ ] •	Again for background variation, you’re using logc<= -2, but even in this example series, there are doses at -3, -2.70, -2.3, and -2, which is 4 dose levels below -2 (rather than the 2 lowest doses as defined earlier).
- [ ] •	Most R users will use the “^” operator, rather than “**”
- [ ] •	In res_low, there are arguments that haven’t been explained that are set to the default in concRespCore(). Can these just be removed to not confuse the reader?
- [ ] •	Additionally, the warning messages may be distracting to the reader.
- [ ] •	Suggest not showing the DT::datatable code, which is just relevant for printing the table on HTML page, right?
- [ ] •	Has this process of bounding the BMD and shifting the BMDL and BMDU accordingly been vetted by a statistician? Is this how it’s done in BMDExpress? Is it appropriate to do the shifting on the uM scale instead of log10uM scale? If it is optimized with log10 concentrations, I would have expected the shift to occur on the log10 scale.
- [ ] Imposing Upper BMD Bounds
- [ ] •	Same comments as above
- [ ] Bounding BMDs with tcplhit2_core & Impacts if BMD is between the BMD Lower Bound and Lowest Dose Tested
- [ ] •	Same comment about DT::datatable

Plotting

- [ ] •	It would help to set up these sections with the framing of concRespCore vs. tcpfilt2_core because I was confused about the flow and the difference between plotting functions by the time I got to the section Plotting All Models from tcplfit2_core
- [ ] •	Fig 9 – It would be helpful to relabel the x- and y-axes. Additionally, can you label the panels by signature?
- [ ] o	Are the lines correctly showing model fits? They don’t look like smooth, fitted curves and don’t look right.
- [ ] o	I can’t see the yellow color on my screen.
- [ ] •	The text and code after Figure 10 seems like it should be deleted.

Plotting All Models From tcplfit2_core

- [ ] •	Suggest not switch to “=” operator from “<-“

Plotting the Winning Model

- [ ] •	I need a reminder about the difference between concRespPlot() and concRespPlot2() by this point.
- [ ] •	Same comment about switching to “=” operator

Plotting Customizations

- [ ] •	There are dplyr functions in here that require tidyverse or dplyr to be loaded or pointed to.
- [ ] •	Check for typos in text

Area Under the Curve (AUC)

- [ ] •	Need function font for get_AUC() in places
- [ ] •	I know this is experimental, but it seems like it would be more streamlined to give get_AUC() the tcplfit2_core object and name of the model and have it pull out the model parameters as part of running the function, rather than requiring the user to do it.
- [ ] •	Biphasic Responses
- [ ] o	The a and b parameters in the text do not match those in the code. Accordingly, Fig. 2 does not have an intercept at x=2 as stated in the legend.
- [ ] o	Can you use the return.abs = TRUE argument in the total_auc calculation, rather than wrapping it within abs()?
- [ ] o	This calculation requires a lot of trust that the user will implement this appropriately. I wonder if it makes sense to modify the get_AUC() function to always return absolute value and to automatically compute the biphasic AUCs appropriately so that the user doesn’t mess it up.
- [ ] o	Additionally, this example is odd in that it doesn’t use an actual fit of a biphasic curve to real or simulated data, it just uses known parameters from an example curve to calculate AUC. This may confuse users and I wonder if it’s best to leave out for now; or modify the example to simulate data with noise, fit the curve, pull out the fitted model parameters, and then calculate AUC.

Model Details

- [ ] •	Please rephrase this sentence for clarity: “Use of the concentration range depends upon particular models ability to show full range of impact of parameter values on curve shape.”
- [ ] •	Please make code chunks readable without scrolling
- [ ] •	Suggest dealing with warning messages to avoid distractions to reader
- [ ] •	The presentation in this section is a little odd because the reader must read the figure legends to understand what they are supposed to get out of them, rather than having explanation in the text and then being referred to the figures.
- [ ] •	Figure 23 – For completeness, please include in the figure legend what the constant values are that b and a are held at in each panel. Same comment for other figures, where applicable.
- [ ] •	Hill - Figure 25 and all other figures shown on log10 concentration scale – I strongly suggest either showing the curves on non-logged scale, or if showing on log-10 scale, increase the resolution substantially and start the concentration at 0.01 or another small positive number (rather than 0) so there is not a discontinuity. The x-axis should go into negative values on the log-10 scale.
- [ ] o	ex_conc3 <- seq(0.01, 100, length.out = 1000) looks much better.
- [ ] •	I’m pretty sure Hill model should be capitalized everywhere because it is a last name.
- [ ] •	Figure 28 – Legend does not match p values used in code.
- [ ] •	The explanation of the impact of p in Exp3 is confusing to me. In Figure 28, black is p=.3, red is p=.9, blue is p=1.2. It doesn’t seem true that the larger p is, the steeper the curve. It probably also depends on whether x is greater than b.
- [ ] •	Exp5 – similar comment as above for statement about p. I think the relative steepness of the curves depends on where you’re looking along the x-axis.

**Comment by brown-jason** [comment]
[Uploading tcplFit2-vignette-notes-LJE.docx…]()
